name: rohan-cdng
replicas: 2


createNamespace: true
namespace: <+infrastructure.namespace>

# Service Type allow you to specify what kind of service you want.
# Possible values for ServiceType are:
# ClusterIP | NodePort | LoadBalancer | ExternalName

serviceType: LoadBalancer

# A Service can map an incoming port to any targetPort.
# targetPort is where application is listening on inside the container.

servicePort: 80
serviceTargetPort: todolist

# Specify all environment variables to be added to the container.
# The following two maps, config and secrets, are put into a ConfigMap
# and a Secret, respectively.
# Both are added to the container environment in podSpec as envFrom source.

env:
  config:
    key1: harnessDemo
  secrets:
    key2: thisSecret
